package de.hype.bingonet.environment.packetconfig

enum class TradeTypeEnvironmentRegistry {
    CATACOMBS_FLOOR_2_300_SCORE,
    CATACOMBS_FLOOR_2_250_SCORE,
    AUTO_SLAYER_UNLOCK,
    CARRY_ENTRANCE_TO_F3_COMPLETION,
    KABOOM_ASSISTANCE,
    OPEN_VIKING,
    ENCHANT_ITEMS,
    CATACOMBS_FLOOR_1_230_SCORE,
    CATACOMBS_FLOOR_1_270_SCORE,
    CARRY_LILY_PAD_GOAL,
    DAILY_MAX_ENCHANTING,
    CARRY_CHALLENGING_ROD,
    CRIMSON_ISLE_BARBARIAN_FACTION,
    SPIDER_ESSENCE_COM_GOAL,
    MINING_COMMISSIONS,
    SLAYER_TIER_4,
    SLAYER_TIER_5,
    SPAWN_SCATHA,
    GIFTS,
    CARRY_INK_SACKS,
    CRIMSON_ISLE_MAGE_FACTION,
    CHUM_BUCKET,
    ;
}
